// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./components/app/Footer.vue')['default']
    FormCreate: typeof import('./components/todos/FormCreateTodo.vue')['default']
    FormLogin: typeof import('./components/auth/FormLogin.vue')['default']
    Header: typeof import('./components/app/Header.vue')['default']
    ViewTodos: typeof import('./components/todos/ViewTodos.vue')['default']
  }
}

export { }
